# -*- coding: utf-8 -*-
"""Brain Segmentation Dataset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nq189aOUqrye50S6I3s5Njzo4lz-4O8v
"""

!pip install pydicom

from google.colab import drive
drive.mount('/content/drive')

!tar -xvf "/content/drive/MyDrive/BRATS/BraTS2021_Training_Data.tar" -C "/content/brats_train"

! du -sh /content/brats_train

len(os.listdir('/content/brats_train'))

import os

import matplotlib.pyplot as plt
import pydicom
filename = '/content/Brats_train/00000/T2w/Image-103.dcm'
ds = pydicom.dcmread(filename)
plt.imshow(ds.pixel_array)

import nibabel as nib
import numpy as np
import matplotlib.pyplot as plt

nii_data.shape

